### ISSUE TITLE
Incorrect Output

### ISSUE THREAD

**Issue by exilonium** [nikhilmwarrier/jee-2024-scraper#5]
I've attempted 46 questions but it's showing 48 attempted also score is off by three..
Does this script consider all cases like:-
- Marked For Review
- Not Answered
- Answered
- Not Attempted and Marked For Review 

Thanks

**Comment by nikhilmwarrier** [comment]
The script considers `Answered` and `Marked For Review`. `Marked For Review` had some problems but these have been fixed (see #4, #8).
  
Please try again and feel free to reopen this issue if the score is still off.

**Comment by exilonium** [comment]
this issue isn't fixed yet now it shows the right amount of correct questions
but it still shows incorrect amount of wrong questions and total attempted questions

also just a quick tip :- Never close an issue before seeing a respond from the OP...Have a nice day 🙂

**Comment by nikhilmwarrier** [comment]
Alright, is the issue still present?
Also can you send a copy of your response sheet? (after clearing out your personal details)
